import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const textRepairReplacements: Array<[string, string]> = [
  ["benef?cios", "benefícios"],
  ["benefï¿½cios", "benefícios"],
  ["benefÃ­cios", "benefícios"],
  ["s?cio", "sócio"],
  ["S?cio", "Sócio"],
  ["Socio", "Sócio"],
  ["sÃ³cio", "sócio"],
  ["SÃ³cio", "Sócio"],
  ["atÃ¯Â¿Â½", "até"],
  ["atï¿½", "até"],
  ["atÃ©", "até"],
  ["n?o", "não"],
  ["N?o", "Não"],
  ["nÃ£o", "não"],
  ["NÃ£o", "Não"],
  ["r?pido", "rápido"],
  ["R?pido", "Rápido"],
  ["rÃ¡pido", "rápido"],
  ["RÃ¡pido", "Rápido"],
  ["?nica", "única"],
  ["?nico", "único"],
  ["Ãºnica", "única"],
  ["Ãºnico", "único"],
  ["Contrase?a", "Contraseña"],
  ["ContraseÃ±a", "Contraseña"],
  ["contin?a", "continúa"],
  ["continÃºa", "continúa"],
  ["A?n", "Aún"],
  ["AÃºn", "Aún"],
  ["Act?vala", "Actívala"],
  ["ActÃ­vala", "Actívala"],
  ["Olvid?", "Olvidé"],
  ["OlvidÃ©", "Olvidé"],
  ["n?mero", "número"],
  ["N?mero", "Número"],
  ["nÃºmero", "número"],
  ["NÃºmero", "Número"],
  ["confirma??o", "confirmação"],
  ["devolu??o", "devolução"],
  ["Devolu??es", "Devoluções"],
  ["Endere?o", "Endereço"],
  ["Separa??o", "Separação"],
  ["distribui??o", "distribuição"],
  ["endere?o", "endereço"],
  ["confirmaci?n", "confirmación"],
  ["devoluci?n", "devolución"],
  ["Direcci?n", "Dirección"],
  ["Preparaci?n", "Preparación"],
  ["Env?o", "Envío"],
  ["distribuci?n", "distribución"],
  ["direcci?n", "dirección"],
  ["?Disfruta", "¡Disfruta"],
  ["Â¡Disfruta", "¡Disfruta"],
  ["simb?lico", "simbólico"],
  ["simbÃ³lico", "simbólico"],
  ["Cap?tulo", "Capítulo"],
  ["CapÃ­tulo", "Capítulo"],
  ["Hist?ria", "História"],
  ["HistÃ³ria", "História"],
  ["tradi??o", "tradição"],
  ["tradiÃ§Ã£o", "tradição"],
  ["est?dio", "estádio"],
  ["Est?dio", "Estádio"],
  ["estÃ¡dio", "estádio"],
  ["EstÃ¡dio", "Estádio"],
  ["tens?o", "tensão"],
  ["tensÃ£o", "tensão"],
  ["lan?amento", "lançamento"],
  ["lan?amentos", "lançamentos"],
  ["Lan?amentos", "Lançamentos"],
  ["lanÃ§amento", "lançamento"],
  ["lanÃ§amentos", "lançamentos"],
  ["LanÃ§amentos", "Lançamentos"],
  ["Constru?da", "Construída"],
  ["ConstruÃ­da", "Construída"],
  ["PresenÃƒÂ§a", "Presença"],
  ["PresenÃ§a", "Presença"],
  ["cole??o", "coleção"],
  ["coleÃ§Ã£o", "coleção"],
  ["Conex?o", "Conexão"],
  ["ConexÃ£o", "Conexão"],
  ["contempor?nea", "contemporânea"],
  ["contemporÃ¢nea", "contemporânea"],
  ["sofistica??o", "sofisticação"],
  ["sofisticaÃ§Ã£o", "sofisticação"],
  ["campa?a", "campaña"],
  ["campaÃ±a", "campaña"],
  ["CampaÃ¯Â¿Â½a", "Campaña"],
  ["tradici?n", "tradición"],
  ["tradiciÃ³n", "tradición"],
  ["fr?o", "frío"],
  ["frÃ­o", "frío"],
  ["f?tbol", "fútbol"],
  ["fÃºtbol", "fútbol"],
  ["emblem?tica", "emblemática"],
  ["emblemÃ¡tica", "emblemática"],
  ["colecci?n", "colección"],
  ["colecciÃ³n", "colección"],
  ["Aqu?", "Aquí"],
  ["AquÃ­", "Aquí"],
  ["Atm?sfera", "Atmósfera"],
  ["AtmÃ³sfera", "Atmósfera"],
  ["Conexi?n", "Conexión"],
  ["ConexiÃ³n", "Conexión"],
  ["ConexiÃ¯Â¿Â½n", "Conexión"],
  ["Despu?s", "Después"],
  ["DespuÃ©s", "Después"],
  ["selecci?n", "selección"],
  ["selecciÃ³n", "selección"],
  ["SeleÃ¯Â¿Â½Ã¯Â¿Â½o", "Seleção"],
  ["im?genes", "imágenes"],
  ["imÃ¡genes", "imágenes"],
  ["palma da m?o", "palma da mão"],
  ["palma da mÃ£o", "palma da mão"],
  ["Acess?rios", "Acessórios"],
  ["AcessÃ³rios", "Acessórios"],
  ["tamb?m", "também"],
  ["tambÃ©m", "também"],
  ["tambiÃ¯Â¿Â½n", "también"],
  ["v?deo", "vídeo"],
  ["vÃ­deo", "vídeo"],
  ["Conte?do", "Conteúdo"],
  ["ConteÃºdo", "Conteúdo"],
  ["m?o", "mão"],
  ["mÃ£o", "mão"],
  ["not?cias", "notícias"],
  ["notÃ­cias", "notícias"],
  ["Suscr?bete", "Suscríbete"],
  ["SuscrÃ­bete", "Suscríbete"],
  ["Categor?as", "Categorías"],
  ["CategorÃ­as", "Categorías"],
  ["L?nea", "Línea"],
  ["LÃ­nea", "Línea"],
  ["S?guenos", "Síguenos"],
  ["SÃ­guenos", "Síguenos"],
  ["Dise?o", "Diseño"],
  ["DiseÃ±o", "Diseño"],
  ["Cu?ntanos", "Cuéntanos"],
  ["CuÃ©ntanos", "Cuéntanos"],
  ["voc?", "você"],
  ["vocÃª", "você"],
  ["? feita", "é feita"],
  ["Ã© feita", "é feita"],
  ["n?o deixa", "não deixa"],
  ["nÃ£o deixa", "não deixa"],
  ["advers?rio", "adversário"],
  ["adversÃ¡rio", "adversário"],
  ["confort?vel", "confortável"],
  ["confortÃ¡vel", "confortável"],
  ["s? essa", "só essa"],
  ["sÃ³ essa", "só essa"],
  ["recomenda??o", "recomendação"],
  ["recomendaÃ§Ã£o", "recomendação"],
  ["Vers?o", "Versão"],
  ["VersÃ£o", "Versão"],
  ["op??es", "opções"],
  ["opÃ§Ãµes", "opções"],
  ["Pe?as", "Peças"],
  ["pe?as", "peças"],
  ["Pe?a", "Peça"],
  ["pe?a", "peça"],
  ["PeÃ§as", "Peças"],
  ["peÃ§as", "peças"],
  ["PeÃ§a", "Peça"],
  ["peÃ§a", "peça"],
  ["Pr?xima", "Próxima"],
  ["PrÃ³xima", "Próxima"],
  ["Cat?logo", "Catálogo"],
  ["CatÃ¡logo", "Catálogo"],
  ["Titular -?", "Titular -"],
  ["Curitiba ? Coritiba", "Curitiba é Coritiba"],
  ["Curitiba Ã© Coritiba", "Curitiba é Coritiba"],
  ["pra quem ? de Coritiba", "pra quem é de Coritiba"],
  ["pra quem Ã© de Coritiba", "pra quem é de Coritiba"],
  ["? a identidade", "é a identidade"],
  ["Ã© a identidade", "é a identidade"],
  ["? a camisa", "É a camisa"],
  ["Ã‰ a camisa", "É a camisa"],
  ["? altura", "à altura"],
  ["Ã  altura", "à altura"],
  ["licenÃ¯Â¿Â½a", "licença"],
  ["histÃ¯Â¿Â½ria", "história"],
  ["vers?o", "versão"],
  ["versÃ£o", "versão"],
  ["j?", "já"],
  ["jÃ¡", "já"],
  ["come?a", "começa"],
  ["comeÃ§a", "começa"],
  ["campe?es", "campeões"],
  ["campeÃµes", "campeões"],
  ["Composi??o", "Composição"],
  ["ComposiÃ§Ã£o", "Composição"],
  ["Poli?ster", "Poliéster"],
  ["PoliÃ©ster", "Poliéster"],
  ["bot?nico", "botânico"],
  ["botÃ¢nico", "botânico"],
  ["sublima??o", "sublimação"],
  ["sublimaÃ§Ã£o", "sublimação"],
  ["refer?ncia", "referência"],
  ["referÃªncia", "referência"],
  ["arquitet?nica", "arquitetônica"],
  ["arquitetÃ´nica", "arquitetônica"],
  ["refor?am", "reforçam"],
  ["reforÃ§am", "reforçam"],
  ["reforï¿½ando", "reforçando"],
  ["bot?o", "botão"],
  ["botÃ£o", "botão"],
  ["Retil?nea", "Retilínea"],
  ["RetilÃ­nea", "Retilínea"],
  ["cora??o", "coração"],
  ["coraÃ§Ã£o", "coração"],
  ["combina??o", "combinação"],
  ["combinaÃ§Ã£o", "combinação"],
  ["atl?tico", "atlético"],
  ["atlÃ©tico", "atlético"],
  ["ecl?tica", "eclética"],
  ["eclÃ©tica", "eclética"],
  ["presen?a", "presença"],
  ["presenÃ§a", "presença"],
  ["f?brica", "fábrica"],
  ["fÃ¡brica", "fábrica"],
  ["r?pida", "rápida"],
  ["rÃ¡pida", "rápida"],
  ["Eleg?ncia", "Elegância"],
  ["ElegÃ¢ncia", "Elegância"],
  ["ventila??o", "ventilação"],
  ["ventilaÃ§Ã£o", "ventilação"],
  ["m?ximos", "máximos"],
  ["mÃ¡ximos", "máximos"],
  ["Atletico", "Atlético"],
  ["AtlÃ©tico", "Atlético"],
  ["Instantanea", "Instantânea"],
  ["InstantÃ¢nea", "Instantânea"],
  ["recomendacao", "recomendação"],
  ["fisica", "física"],
  ["AnÃ¡lise", "Análise"],
  ["Analise", "Análise"],
  ["padrao", "padrão"],
  ["padrÃ£o", "padrão"],
  ["estandar", "estándar"],
  ["estÃ¡ndar", "estándar"],
  ["Caida", "Caída"],
  ["CaÃ­da", "Caída"],
  ["Mas ajustada", "Más ajustada"],
  ["MÃ¡s ajustada", "Más ajustada"],
  ["Mas holgada", "Más holgada"],
  ["MÃ¡s holgada", "Más holgada"],
  ["analisis", "análisis"],
  ["anÃ¡lisis", "análisis"],
  ["prefer?ncia", "preferência"],
  ["preferÃªncia", "preferência"],
  ["Portugu?s", "Português"],
  ["PortuguÃªs", "Português"],
  ["Ingl?s", "Inglês"],
  ["InglÃªs", "Inglês"],
  ["Espa?ol", "Español"],
  ["EspaÃ±ol", "Español"],
  ["experi?ncia", "experiência"],
  ["experiÃªncia", "experiência"],
  ["MÃ¯Â¿Â½s", "Más"],
  ["m?s natural", "más natural"],
  ["mÃ¡s natural", "más natural"],
  ["tensiÃ¯Â¿Â½n", "tensión"],
  ["contemporÃ¯Â¿Â½neo", "contemporáneo"],
  ["sofisticaciÃ¯Â¿Â½n", "sofisticación"],
  ["AquÃ¯Â¿Â½", "Aquí"],
  ["energÃ¯Â¿Â½a", "energía"],
  ["decisiÃ¯Â¿Â½n", "decisión"],
  ["tambienn", "también"],
  ["â†", "←"],
  ["? Voltar para o Login", "← Voltar para o Login"],
  ["? Back to Login", "← Back to Login"],
  ["? Volver al Login", "← Volver al Login"],
  ["? Voltar", "← Voltar"],
  ["? Back", "← Back"],
  ["? Volver", "← Volver"],
  ["? Refazer Perfil", "← Refazer Perfil"],
  ["Avan?ar", "Avançar"],
  ["AvanÃ§ar", "Avançar"],
  ["Ã¢Å“Â¦", "✦"],
  ["âœ¦", "✦"],
  ["ï¿½aï¿½", "✦"],
];

export function repairText(value: string): string {
  return textRepairReplacements.reduce(
    (current, [from, to]) => current.split(from).join(to),
    value,
  );
}

export function repairDeepStrings<T>(value: T): T {
  if (typeof value === "string") {
    return repairText(value) as T;
  }

  if (Array.isArray(value)) {
    return value.map((item) => repairDeepStrings(item)) as T;
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, nestedValue]) => [
        key,
        repairDeepStrings(nestedValue),
      ]),
    ) as T;
  }

  return value;
}
